# Generated by Django 6.0.8 on 2026-08-31 05:22

import json

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models

PAGE_TABLES = (
    "base_formpage",
    "base_gallerypage",
    "base_homepage",
    "base_standardpage",
)


def _update_case_study_headings(schema_editor, add_heading):
    quote_name = schema_editor.connection.ops.quote_name
    with schema_editor.connection.cursor() as cursor:
        for table_name in PAGE_TABLES:
            table = quote_name(table_name)
            cursor.execute(f"SELECT page_ptr_id, body FROM {table}")
            for page_id, stored_body in cursor.fetchall():
                body = (
                    json.loads(stored_body)
                    if isinstance(stored_body, str)
                    else stored_body
                )
                changed = False
                for block in body or []:
                    if block.get("type") != "case_study":
                        continue
                    value = block.get("value")
                    if not isinstance(value, dict):
                        continue
                    if add_heading and "security_controls_heading" not in value:
                        value["security_controls_heading"] = "資安控制重點"
                        changed = True
                    elif not add_heading and "security_controls_heading" in value:
                        del value["security_controls_heading"]
                        changed = True
                if changed:
                    cursor.execute(
                        f"UPDATE {table} SET body = %s WHERE page_ptr_id = %s",
                        [json.dumps(body, ensure_ascii=False), page_id],
                    )


def add_case_study_headings(apps, schema_editor):
    _update_case_study_headings(schema_editor, add_heading=True)


def remove_case_study_headings(apps, schema_editor):
    _update_case_study_headings(schema_editor, add_heading=False)


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0029_add_semi_site_settings"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="hero_badge",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="homepage",
            name="secondary_hero_cta",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Secondary hero CTA",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="secondary_hero_cta_fragment",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional anchor ID without the leading #.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="secondary_hero_cta_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Secondary hero CTA link",
            ),
        ),
        migrations.AddField(
            model_name="standardpage",
            name="secondary_section_heading",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="standardpage",
            name="secondary_section_introduction",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="standardpage",
            name="secondary_section_kicker",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="standardpage",
            name="section_heading",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="standardpage",
            name="section_kicker",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.RunPython(
            add_case_study_headings,
            remove_case_study_headings,
        ),
        migrations.AlterField(
            model_name="formpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading_block", 2),
                    ("paragraph_block", 3),
                    ("image_block", 6),
                    ("block_quote", 12),
                    ("card_grid", 21),
                    ("document_table", 25),
                    ("process_steps", 32),
                    ("case_study", 38),
                    ("embed_block", 39),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [("h2", "H2"), ("h3", "H3"), ("h4", "H4")],
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 0), ("size", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "description": "A rich text paragraph",
                            "icon": "pilcrow",
                            "preview_value": '\n            <h2>Our bread pledge</h2>\n            <p>As a bakery, <b>breads</b> have <i>always</i> been in our hearts.\n            <a href="https://en.wikipedia.org/wiki/Staple_food">Staple foods</a>\n            are essential for society, and – bread is the tastiest of all.\n            We love to transform batters and doughs into baked goods with a firm\n            dry crust and fluffy center.</p>\n            ',
                            "template": "blocks/paragraph_block.html",
                        },
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 4), ("caption", 5), ("attribution", 5)]],
                        {},
                    ),
                    7: ("wagtail.blocks.TextBlock", (), {}),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"blank": True, "label": "e.g. Mary Berry", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default"),
                                ("highlight", "Highlight"),
                            ],
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("default", "Default"), ("large", "Large")],
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("theme", 9), ("text_size", 10)]],
                        {"collapsed": True},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 7), ("attribute_name", 8), ("settings", 11)]],
                        {},
                    ),
                    13: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    14: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("two", "Two columns"),
                                ("three", "Three columns"),
                                ("four", "Four columns"),
                            ]
                        },
                    ),
                    16: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    17: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 13),
                                ("internal_page", 17),
                                ("external_url", 5),
                                ("fragment", 5),
                            ]
                        ],
                        {"required": False},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("number", 5),
                                ("eyebrow", 5),
                                ("title", 13),
                                ("summary", 16),
                                ("link", 18),
                            ]
                        ],
                        {},
                    ),
                    20: ("wagtail.blocks.ListBlock", (19,), {"min_num": 1}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("eyebrow", 5),
                                ("heading", 13),
                                ("introduction", 14),
                                ("layout", 15),
                                ("cards", 20),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.RegexBlock",
                        ("[A-Za-z][A-Za-z0-9_-]*\\Z",),
                        {
                            "error_messages": {
                                "invalid": "Use letters, numbers, hyphens, and underscores only."
                            }
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("number", 13),
                                ("title", 13),
                                ("summary", 16),
                                ("status", 13),
                                ("link", 18),
                            ]
                        ],
                        {},
                    ),
                    24: ("wagtail.blocks.ListBlock", (23,), {"min_num": 1}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 13),
                                ("caption", 5),
                                ("anchor_id", 22),
                                ("rows", 24),
                            ]
                        ],
                        {},
                    ),
                    26: ("wagtail.blocks.CharBlock", (), {}),
                    27: ("wagtail.blocks.ListBlock", (26,), {"required": False}),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 13),
                                ("internal_page", 17),
                                ("external_url", 5),
                                ("fragment", 5),
                            ]
                        ],
                        {},
                    ),
                    29: ("wagtail.blocks.ListBlock", (28,), {"required": False}),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("number", 13),
                                ("title", 13),
                                ("summary", 16),
                                ("checklist", 27),
                                ("resource_links", 29),
                            ]
                        ],
                        {},
                    ),
                    31: ("wagtail.blocks.ListBlock", (30,), {"min_num": 1}),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("introduction", 14), ("steps", 31)]],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 13), ("value", 13)]],
                        {},
                    ),
                    34: ("wagtail.blocks.ListBlock", (33,), {"min_num": 1}),
                    35: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 13), ("summary", 16)]],
                        {},
                    ),
                    37: ("wagtail.blocks.ListBlock", (36,), {"min_num": 1}),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("case_label", 13),
                                ("company", 13),
                                ("product", 13),
                                ("certification_status", 13),
                                ("summary", 16),
                                ("metadata", 34),
                                ("equipment_image", 4),
                                ("equipment_caption", 5),
                                ("challenge_heading", 13),
                                ("challenge", 35),
                                ("solution_heading", 13),
                                ("solution", 35),
                                ("security_controls_heading", 13),
                                ("security_controls", 37),
                                ("outcome_image", 4),
                                ("outcome_caption", 5),
                            ]
                        ],
                        {},
                    ),
                    39: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "description": "An embedded video or other media",
                            "help_text": "Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks",
                            "icon": "media",
                            "preview_template": "base/preview/static_embed_block.html",
                            "preview_value": "https://www.youtube.com/watch?v=mwrGSfiB1Mg",
                            "template": "blocks/embed_block.html",
                        },
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="gallerypage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading_block", 2),
                    ("paragraph_block", 3),
                    ("image_block", 6),
                    ("block_quote", 12),
                    ("card_grid", 21),
                    ("document_table", 25),
                    ("process_steps", 32),
                    ("case_study", 38),
                    ("embed_block", 39),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [("h2", "H2"), ("h3", "H3"), ("h4", "H4")],
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 0), ("size", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "description": "A rich text paragraph",
                            "icon": "pilcrow",
                            "preview_value": '\n            <h2>Our bread pledge</h2>\n            <p>As a bakery, <b>breads</b> have <i>always</i> been in our hearts.\n            <a href="https://en.wikipedia.org/wiki/Staple_food">Staple foods</a>\n            are essential for society, and – bread is the tastiest of all.\n            We love to transform batters and doughs into baked goods with a firm\n            dry crust and fluffy center.</p>\n            ',
                            "template": "blocks/paragraph_block.html",
                        },
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 4), ("caption", 5), ("attribution", 5)]],
                        {},
                    ),
                    7: ("wagtail.blocks.TextBlock", (), {}),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"blank": True, "label": "e.g. Mary Berry", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default"),
                                ("highlight", "Highlight"),
                            ],
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("default", "Default"), ("large", "Large")],
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("theme", 9), ("text_size", 10)]],
                        {"collapsed": True},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 7), ("attribute_name", 8), ("settings", 11)]],
                        {},
                    ),
                    13: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    14: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("two", "Two columns"),
                                ("three", "Three columns"),
                                ("four", "Four columns"),
                            ]
                        },
                    ),
                    16: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    17: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 13),
                                ("internal_page", 17),
                                ("external_url", 5),
                                ("fragment", 5),
                            ]
                        ],
                        {"required": False},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("number", 5),
                                ("eyebrow", 5),
                                ("title", 13),
                                ("summary", 16),
                                ("link", 18),
                            ]
                        ],
                        {},
                    ),
                    20: ("wagtail.blocks.ListBlock", (19,), {"min_num": 1}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("eyebrow", 5),
                                ("heading", 13),
                                ("introduction", 14),
                                ("layout", 15),
                                ("cards", 20),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.RegexBlock",
                        ("[A-Za-z][A-Za-z0-9_-]*\\Z",),
                        {
                            "error_messages": {
                                "invalid": "Use letters, numbers, hyphens, and underscores only."
                            }
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("number", 13),
                                ("title", 13),
                                ("summary", 16),
                                ("status", 13),
                                ("link", 18),
                            ]
                        ],
                        {},
                    ),
                    24: ("wagtail.blocks.ListBlock", (23,), {"min_num": 1}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 13),
                                ("caption", 5),
                                ("anchor_id", 22),
                                ("rows", 24),
                            ]
                        ],
                        {},
                    ),
                    26: ("wagtail.blocks.CharBlock", (), {}),
                    27: ("wagtail.blocks.ListBlock", (26,), {"required": False}),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 13),
                                ("internal_page", 17),
                                ("external_url", 5),
                                ("fragment", 5),
                            ]
                        ],
                        {},
                    ),
                    29: ("wagtail.blocks.ListBlock", (28,), {"required": False}),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("number", 13),
                                ("title", 13),
                                ("summary", 16),
                                ("checklist", 27),
                                ("resource_links", 29),
                            ]
                        ],
                        {},
                    ),
                    31: ("wagtail.blocks.ListBlock", (30,), {"min_num": 1}),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("introduction", 14), ("steps", 31)]],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 13), ("value", 13)]],
                        {},
                    ),
                    34: ("wagtail.blocks.ListBlock", (33,), {"min_num": 1}),
                    35: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 13), ("summary", 16)]],
                        {},
                    ),
                    37: ("wagtail.blocks.ListBlock", (36,), {"min_num": 1}),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("case_label", 13),
                                ("company", 13),
                                ("product", 13),
                                ("certification_status", 13),
                                ("summary", 16),
                                ("metadata", 34),
                                ("equipment_image", 4),
                                ("equipment_caption", 5),
                                ("challenge_heading", 13),
                                ("challenge", 35),
                                ("solution_heading", 13),
                                ("solution", 35),
                                ("security_controls_heading", 13),
                                ("security_controls", 37),
                                ("outcome_image", 4),
                                ("outcome_caption", 5),
                            ]
                        ],
                        {},
                    ),
                    39: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "description": "An embedded video or other media",
                            "help_text": "Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks",
                            "icon": "media",
                            "preview_template": "base/preview/static_embed_block.html",
                            "preview_value": "https://www.youtube.com/watch?v=mwrGSfiB1Mg",
                            "template": "blocks/embed_block.html",
                        },
                    ),
                },
                verbose_name="Page body",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading_block", 2),
                    ("paragraph_block", 3),
                    ("image_block", 6),
                    ("block_quote", 12),
                    ("card_grid", 21),
                    ("document_table", 25),
                    ("process_steps", 32),
                    ("case_study", 38),
                    ("embed_block", 39),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [("h2", "H2"), ("h3", "H3"), ("h4", "H4")],
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 0), ("size", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "description": "A rich text paragraph",
                            "icon": "pilcrow",
                            "preview_value": '\n            <h2>Our bread pledge</h2>\n            <p>As a bakery, <b>breads</b> have <i>always</i> been in our hearts.\n            <a href="https://en.wikipedia.org/wiki/Staple_food">Staple foods</a>\n            are essential for society, and – bread is the tastiest of all.\n            We love to transform batters and doughs into baked goods with a firm\n            dry crust and fluffy center.</p>\n            ',
                            "template": "blocks/paragraph_block.html",
                        },
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 4), ("caption", 5), ("attribution", 5)]],
                        {},
                    ),
                    7: ("wagtail.blocks.TextBlock", (), {}),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"blank": True, "label": "e.g. Mary Berry", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default"),
                                ("highlight", "Highlight"),
                            ],
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("default", "Default"), ("large", "Large")],
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("theme", 9), ("text_size", 10)]],
                        {"collapsed": True},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 7), ("attribute_name", 8), ("settings", 11)]],
                        {},
                    ),
                    13: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    14: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("two", "Two columns"),
                                ("three", "Three columns"),
                                ("four", "Four columns"),
                            ]
                        },
                    ),
                    16: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    17: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 13),
                                ("internal_page", 17),
                                ("external_url", 5),
                                ("fragment", 5),
                            ]
                        ],
                        {"required": False},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("number", 5),
                                ("eyebrow", 5),
                                ("title", 13),
                                ("summary", 16),
                                ("link", 18),
                            ]
                        ],
                        {},
                    ),
                    20: ("wagtail.blocks.ListBlock", (19,), {"min_num": 1}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("eyebrow", 5),
                                ("heading", 13),
                                ("introduction", 14),
                                ("layout", 15),
                                ("cards", 20),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.RegexBlock",
                        ("[A-Za-z][A-Za-z0-9_-]*\\Z",),
                        {
                            "error_messages": {
                                "invalid": "Use letters, numbers, hyphens, and underscores only."
                            }
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("number", 13),
                                ("title", 13),
                                ("summary", 16),
                                ("status", 13),
                                ("link", 18),
                            ]
                        ],
                        {},
                    ),
                    24: ("wagtail.blocks.ListBlock", (23,), {"min_num": 1}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 13),
                                ("caption", 5),
                                ("anchor_id", 22),
                                ("rows", 24),
                            ]
                        ],
                        {},
                    ),
                    26: ("wagtail.blocks.CharBlock", (), {}),
                    27: ("wagtail.blocks.ListBlock", (26,), {"required": False}),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 13),
                                ("internal_page", 17),
                                ("external_url", 5),
                                ("fragment", 5),
                            ]
                        ],
                        {},
                    ),
                    29: ("wagtail.blocks.ListBlock", (28,), {"required": False}),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("number", 13),
                                ("title", 13),
                                ("summary", 16),
                                ("checklist", 27),
                                ("resource_links", 29),
                            ]
                        ],
                        {},
                    ),
                    31: ("wagtail.blocks.ListBlock", (30,), {"min_num": 1}),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("introduction", 14), ("steps", 31)]],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 13), ("value", 13)]],
                        {},
                    ),
                    34: ("wagtail.blocks.ListBlock", (33,), {"min_num": 1}),
                    35: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 13), ("summary", 16)]],
                        {},
                    ),
                    37: ("wagtail.blocks.ListBlock", (36,), {"min_num": 1}),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("case_label", 13),
                                ("company", 13),
                                ("product", 13),
                                ("certification_status", 13),
                                ("summary", 16),
                                ("metadata", 34),
                                ("equipment_image", 4),
                                ("equipment_caption", 5),
                                ("challenge_heading", 13),
                                ("challenge", 35),
                                ("solution_heading", 13),
                                ("solution", 35),
                                ("security_controls_heading", 13),
                                ("security_controls", 37),
                                ("outcome_image", 4),
                                ("outcome_caption", 5),
                            ]
                        ],
                        {},
                    ),
                    39: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "description": "An embedded video or other media",
                            "help_text": "Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks",
                            "icon": "media",
                            "preview_template": "base/preview/static_embed_block.html",
                            "preview_value": "https://www.youtube.com/watch?v=mwrGSfiB1Mg",
                            "template": "blocks/embed_block.html",
                        },
                    ),
                },
                verbose_name="Home content block",
            ),
        ),
        migrations.AlterField(
            model_name="standardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading_block", 2),
                    ("paragraph_block", 3),
                    ("image_block", 6),
                    ("block_quote", 12),
                    ("card_grid", 21),
                    ("document_table", 25),
                    ("process_steps", 32),
                    ("case_study", 38),
                    ("embed_block", 39),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [("h2", "H2"), ("h3", "H3"), ("h4", "H4")],
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 0), ("size", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "description": "A rich text paragraph",
                            "icon": "pilcrow",
                            "preview_value": '\n            <h2>Our bread pledge</h2>\n            <p>As a bakery, <b>breads</b> have <i>always</i> been in our hearts.\n            <a href="https://en.wikipedia.org/wiki/Staple_food">Staple foods</a>\n            are essential for society, and – bread is the tastiest of all.\n            We love to transform batters and doughs into baked goods with a firm\n            dry crust and fluffy center.</p>\n            ',
                            "template": "blocks/paragraph_block.html",
                        },
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 4), ("caption", 5), ("attribution", 5)]],
                        {},
                    ),
                    7: ("wagtail.blocks.TextBlock", (), {}),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"blank": True, "label": "e.g. Mary Berry", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default"),
                                ("highlight", "Highlight"),
                            ],
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("default", "Default"), ("large", "Large")],
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("theme", 9), ("text_size", 10)]],
                        {"collapsed": True},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 7), ("attribute_name", 8), ("settings", 11)]],
                        {},
                    ),
                    13: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    14: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("two", "Two columns"),
                                ("three", "Three columns"),
                                ("four", "Four columns"),
                            ]
                        },
                    ),
                    16: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    17: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 13),
                                ("internal_page", 17),
                                ("external_url", 5),
                                ("fragment", 5),
                            ]
                        ],
                        {"required": False},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("number", 5),
                                ("eyebrow", 5),
                                ("title", 13),
                                ("summary", 16),
                                ("link", 18),
                            ]
                        ],
                        {},
                    ),
                    20: ("wagtail.blocks.ListBlock", (19,), {"min_num": 1}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("eyebrow", 5),
                                ("heading", 13),
                                ("introduction", 14),
                                ("layout", 15),
                                ("cards", 20),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.RegexBlock",
                        ("[A-Za-z][A-Za-z0-9_-]*\\Z",),
                        {
                            "error_messages": {
                                "invalid": "Use letters, numbers, hyphens, and underscores only."
                            }
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("number", 13),
                                ("title", 13),
                                ("summary", 16),
                                ("status", 13),
                                ("link", 18),
                            ]
                        ],
                        {},
                    ),
                    24: ("wagtail.blocks.ListBlock", (23,), {"min_num": 1}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 13),
                                ("caption", 5),
                                ("anchor_id", 22),
                                ("rows", 24),
                            ]
                        ],
                        {},
                    ),
                    26: ("wagtail.blocks.CharBlock", (), {}),
                    27: ("wagtail.blocks.ListBlock", (26,), {"required": False}),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 13),
                                ("internal_page", 17),
                                ("external_url", 5),
                                ("fragment", 5),
                            ]
                        ],
                        {},
                    ),
                    29: ("wagtail.blocks.ListBlock", (28,), {"required": False}),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("number", 13),
                                ("title", 13),
                                ("summary", 16),
                                ("checklist", 27),
                                ("resource_links", 29),
                            ]
                        ],
                        {},
                    ),
                    31: ("wagtail.blocks.ListBlock", (30,), {"min_num": 1}),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("introduction", 14), ("steps", 31)]],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 13), ("value", 13)]],
                        {},
                    ),
                    34: ("wagtail.blocks.ListBlock", (33,), {"min_num": 1}),
                    35: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 13), ("summary", 16)]],
                        {},
                    ),
                    37: ("wagtail.blocks.ListBlock", (36,), {"min_num": 1}),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("case_label", 13),
                                ("company", 13),
                                ("product", 13),
                                ("certification_status", 13),
                                ("summary", 16),
                                ("metadata", 34),
                                ("equipment_image", 4),
                                ("equipment_caption", 5),
                                ("challenge_heading", 13),
                                ("challenge", 35),
                                ("solution_heading", 13),
                                ("solution", 35),
                                ("security_controls_heading", 13),
                                ("security_controls", 37),
                                ("outcome_image", 4),
                                ("outcome_caption", 5),
                            ]
                        ],
                        {},
                    ),
                    39: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "description": "An embedded video or other media",
                            "help_text": "Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks",
                            "icon": "media",
                            "preview_template": "base/preview/static_embed_block.html",
                            "preview_value": "https://www.youtube.com/watch?v=mwrGSfiB1Mg",
                            "template": "blocks/embed_block.html",
                        },
                    ),
                },
                verbose_name="Page body",
            ),
        ),
    ]
