# Generated by Django 6.0.8 on 2026-08-31 05:30

import uuid

import django.db.models.deletion
import wagtail.models.preview
from django.db import migrations, models

SEMI_FOOTER_INTRODUCTION = "若有合規輔導或技術疑問，歡迎聯絡推動辦公室。"


def copy_site_settings_to_localized_content(apps, schema_editor):
    Locale = apps.get_model("wagtailcore", "Locale")
    SiteSettings = apps.get_model("base", "SiteSettings")
    LocalizedSiteContent = apps.get_model("base", "LocalizedSiteContent")
    locale, _ = Locale.objects.get_or_create(language_code="zh-hant")

    for site_settings in SiteSettings.objects.all().iterator():
        is_semi_site = "SEMI E187" in " ".join(
            (site_settings.title_suffix, site_settings.site_name)
        )
        LocalizedSiteContent.objects.update_or_create(
            site_id=site_settings.site_id,
            locale_id=locale.pk,
            defaults={
                "brand_label": "認驗證制度" if is_semi_site else "",
                "title_suffix": site_settings.title_suffix,
                "site_name": site_settings.site_name,
                "site_tagline": site_settings.site_tagline,
                "contact_heading": site_settings.contact_heading,
                "contact_name": site_settings.contact_name,
                "contact_context": site_settings.contact_context,
                "footer_introduction": (
                    SEMI_FOOTER_INTRODUCTION if is_semi_site else ""
                ),
                "organisation_text": site_settings.organisation_text,
                "live": True,
            },
        )


def restore_localized_content_to_site_settings(apps, schema_editor):
    Locale = apps.get_model("wagtailcore", "Locale")
    SiteSettings = apps.get_model("base", "SiteSettings")
    LocalizedSiteContent = apps.get_model("base", "LocalizedSiteContent")
    locale = Locale.objects.filter(language_code="zh-hant").first()
    if locale is None:
        return

    for site_settings in SiteSettings.objects.all().iterator():
        content = LocalizedSiteContent.objects.filter(
            site_id=site_settings.site_id,
            locale_id=locale.pk,
        ).first()
        if content is None:
            continue
        for field_name in (
            "title_suffix",
            "site_name",
            "site_tagline",
            "contact_heading",
            "contact_name",
            "contact_context",
            "organisation_text",
        ):
            setattr(site_settings, field_name, getattr(content, field_name))
        site_settings.save()


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0030_add_semi_editorial_fields"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalizedSiteContent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "translation_key",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "live",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="live"
                    ),
                ),
                (
                    "has_unpublished_changes",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        verbose_name="has unpublished changes",
                    ),
                ),
                (
                    "first_published_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="first published at",
                    ),
                ),
                (
                    "last_published_at",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="last published at"
                    ),
                ),
                (
                    "go_live_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="go live date/time"
                    ),
                ),
                (
                    "expire_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expiry date/time"
                    ),
                ),
                (
                    "expired",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="expired"
                    ),
                ),
                (
                    "brand_label",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "title_suffix",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("site_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "site_tagline",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "contact_heading",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "contact_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "contact_context",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("footer_introduction", models.TextField(blank=True, default="")),
                ("organisation_text", models.TextField(blank=True, default="")),
                (
                    "latest_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="latest revision",
                    ),
                ),
                (
                    "live_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="live revision",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                        verbose_name="locale",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "localized site content",
                "verbose_name_plural": "localized site content",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site", "locale"),
                        name="unique_site_content_per_site_locale",
                    )
                ],
                "unique_together": {("translation_key", "locale")},
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
        migrations.RunPython(
            copy_site_settings_to_localized_content,
            restore_localized_content_to_site_settings,
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="contact_context",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="contact_heading",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="contact_name",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="organisation_text",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="site_name",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="site_tagline",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="title_suffix",
        ),
    ]
