# Generated by Django 6.0.8 on 2026-09-10 06:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0031_localizedsitecontent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitesettings",
            options={
                "verbose_name": "SEMI E187 導覽與聯絡設定",
                "verbose_name_plural": "SEMI E187 導覽與聯絡設定",
            },
        ),
    ]
