# Generated by Django 6.0.8 on 2026-09-10 08:13

from django.db import migrations, models


def copy_contact_details_to_localized_content(apps, schema_editor):
    SiteSettings = apps.get_model("base", "SiteSettings")
    LocalizedSiteContent = apps.get_model("base", "LocalizedSiteContent")

    for site_settings in SiteSettings.objects.all().iterator():
        LocalizedSiteContent.objects.filter(site_id=site_settings.site_id).update(
            contact_phone=site_settings.contact_phone,
            contact_email=site_settings.contact_email,
        )


def restore_contact_details_to_site_settings(apps, schema_editor):
    SiteSettings = apps.get_model("base", "SiteSettings")
    LocalizedSiteContent = apps.get_model("base", "LocalizedSiteContent")

    for site_settings in SiteSettings.objects.all().iterator():
        content = (
            LocalizedSiteContent.objects.filter(
                site_id=site_settings.site_id,
                locale__language_code="zh-hant",
            ).first()
            or LocalizedSiteContent.objects.filter(
                site_id=site_settings.site_id
            ).first()
        )
        if content is None:
            continue
        site_settings.contact_phone = content.contact_phone
        site_settings.contact_email = content.contact_email
        site_settings.save(update_fields=("contact_phone", "contact_email"))


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0033_alter_formpage_body_alter_gallerypage_body_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitesettings",
            options={
                "verbose_name": "SEMI E187 導覽設定",
                "verbose_name_plural": "SEMI E187 導覽設定",
            },
        ),
        migrations.AddField(
            model_name="localizedsitecontent",
            name="contact_email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="聯絡信箱"
            ),
        ),
        migrations.AddField(
            model_name="localizedsitecontent",
            name="contact_phone",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="聯絡電話"
            ),
        ),
        migrations.RunPython(
            copy_contact_details_to_localized_content,
            restore_contact_details_to_site_settings,
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="contact_phone",
        ),
    ]
