# Generated by Django 6.0.8 on 2026-09-14 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_security', '0002_bootstrap_existing_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasskeyCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.CharField(max_length=1024, unique=True)),
                ('credential_public_key', models.BinaryField()),
                ('user_handle', models.BinaryField(max_length=64)),
                ('sign_count', models.PositiveBigIntegerField(default=0)),
                ('device_type', models.CharField(blank=True, max_length=32)),
                ('backed_up', models.BooleanField(default=False)),
                ('transports', models.JSONField(blank=True, default=list)),
                ('label', models.CharField(default='Windows Hello', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkey_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id', 'created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PasskeyAuditEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40)),
                ('success', models.BooleanField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passkey_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passkey_audit_events', to=settings.AUTH_USER_MODEL)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='account_security.passkeycredential')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PasskeyEnrolment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_digest', models.CharField(max_length=64, unique=True)),
                ('disable_password_on_success', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_passkey_enrolments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkey_enrolments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='passkeycredential',
            index=models.Index(fields=['user', 'revoked_at'], name='passkey_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='passkeyauditevent',
            index=models.Index(fields=['-created_at'], name='passkey_event_time_idx'),
        ),
        migrations.AddIndex(
            model_name='passkeyauditevent',
            index=models.Index(fields=['user', '-created_at'], name='passkey_event_user_idx'),
        ),
        migrations.AddIndex(
            model_name='passkeyenrolment',
            index=models.Index(fields=['user', 'expires_at'], name='passkey_user_expiry_idx'),
        ),
    ]
