# Generated by Django 6.0.8 on 2026-09-14 08:27

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def revoke_duplicate_pending_enrolments(apps, schema_editor):
    enrolment_model = apps.get_model("account_security", "PasskeyEnrolment")
    pending = enrolment_model.objects.filter(
        consumed_at__isnull=True,
        revoked_at__isnull=True,
    ).order_by("user_id", "-created_at", "-pk")
    newest_by_user = set()
    duplicate_ids = []
    for enrolment in pending.iterator():
        if enrolment.user_id in newest_by_user:
            duplicate_ids.append(enrolment.pk)
        else:
            newest_by_user.add(enrolment.user_id)
    if duplicate_ids:
        enrolment_model.objects.filter(pk__in=duplicate_ids).update(
            revoked_at=timezone.now()
        )


class Migration(migrations.Migration):

    dependencies = [
        ('account_security', '0003_passkeycredential_passkeyauditevent_passkeyenrolment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            revoke_duplicate_pending_enrolments,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='passkeyenrolment',
            constraint=models.UniqueConstraint(condition=models.Q(('consumed_at__isnull', True), ('revoked_at__isnull', True)), fields=('user',), name='passkey_one_pending_per_user'),
        ),
    ]
