# Generated by Django 6.0.8 on 2026-10-05 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_security', '0006_allow_deleting_passkey_enrolment_creators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FastIdUserLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_key', models.CharField(max_length=128)),
                ('external_user_id', models.CharField(max_length=128)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fast_id_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fast-ID user link',
                'verbose_name_plural': 'Fast-ID user links',
                'constraints': [models.UniqueConstraint(fields=('tenant_key', 'external_user_id'), name='fast_id_tenant_external_user_unique')],
            },
        ),
    ]
